### ISSUE TITLE
Projets manquants

### ISSUE THREAD

**Issue by bernard-ng** [sauveurkilupula12/php-trainig#2]
Il manque deux projets, celui des heurs supplémentaires et la conversion usd cdf

**Comment by sauveurkilupula12** [comment]
Bonjour monsieur Bernard, oui exactement, le pc s'est éteint bien avant que
je ne finisse.

Je pourrai le faire ce soir à la maison si le courant se rétablit : mon pc
de la maison n'a pas de batterie c'est qui me bloque un peu.🙏

Le mar. 4 juin 2024 à 3:03 PM, Bernard Ngandu ***@***.***> a
écrit :
